pipeline {
  agent any

  parameters {
    string(name: 'INSTANCE_NAME', defaultValue: 'my-ec2-instance', description: 'EC2 Instance Name')
  }

  stages {
    stage('Terraform Init') {
      steps {
        sh 'terraform init'
      }
    }

    stage('Terraform Plan') {
      steps {
        sh "terraform plan -var=\"instance_name=${params.INSTANCE_NAME}\""
      }
    }

    stage('Terraform Apply') {
      steps {
        sh "terraform apply -auto-approve -var=\"instance_name=${params.INSTANCE_NAME}\""
      }
    }
  }
}
