pipeline {
    agent any

    parameters {
        string(name: 'AWS_REGION', defaultValue: 'us-east-2', description: 'AWS region to deploy resources')
        string(name: 'BUCKET_NAME', defaultValue: 'my-terra-bucket', description: 'Name of the S3 bucket')
    }

    environment {
        TF_VAR_bucket_name = "${params.BUCKET_NAME}"
        TF_VAR_region = "${params.AWS_REGION}"
    }

    stages {
        stage('Checkout Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/riteshbehal/TerraForm.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('s3') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('s3') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('s3') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}
