pipeline {
    agent any

    parameters {
    string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS region to deploy resources')
    string(name: 'BUCKET_NAME', defaultValue: 'my-terra-bucket', description: 'Name of the S3 bucket')
}

    stages {
        stage('Checkout Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/riteshbehal/TerraForm.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('s3') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('s3') {
                    sh """
                        terraform plan \
                        -var="bucket_name=${params.BUCKET_NAME}" \
                        -var="region=${params.AWS_REGION}"
                    """
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('s3') {
                    sh """
                        terraform apply -auto-approve \
                        -var="bucket_name=${params.BUCKET_NAME}" \
                        -var="region=${params.AWS_REGION}"
                    """
                }
            }
        }
    }
}
